
DROP DATABASE classcircle;

SET NAMES 'utf8mb4';

CREATE DATABASE IF NOT EXISTS classcircle
	CHARACTER SET = 'utf8mb4'
	COLLATE 'utf8mb4_unicode_ci';

USE classcircle;

CREATE TABLE IF NOT EXISTS students(
	studentid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	forename VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	birthday DATE,
	email VARCHAR(50) NOT NULL,
	siblings VARCHAR(50),
	imageName VARCHAR(256),
	visionScore VARCHAR(10),
	eyeColor VARCHAR(20),
	piercingTattoos VARCHAR(30),
	favouriteSong VARCHAR(50),
	chickenCrossReason VARCHAR(50),
	quote VARCHAR(500),
	hobbies VARCHAR(300),
	pets VARCHAR(20),
	allergies VARCHAR(20),
	schoolBeforeHTL VARCHAR(20),
	burgerPizzaAvocado VARCHAR(20),
	favouriteSubject VARCHAR(30),
	favouriteColor VARCHAR(20),
	phone VARCHAR(20),
	favouriteFood VARCHAR(40),
	favouriteMedia VARCHAR(300),
	specialClassFunction VARCHAR(30),
	socialmedia VARCHAR(200),
	CONSTRAINT PRIMARY KEY(studentid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci; 

CREATE TABLE IF NOT EXISTS comments(
	commentid INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	message VARCHAR(500) NOT NULL,
	dat DATE NOT NULL,
	studentid INTEGER UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY(studentid) REFERENCES students(studentid),
	CONSTRAINT PRIMARY KEY(commentid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO students (
	forename,
	lastname,
	birthday,
	email,
	siblings,
	imageName,
	visionScore,
	eyeColor,
	piercingTattoos,
	favouriteSong,
	chickenCrossReason,
	quote,
	hobbies,
	pets,
	allergies,
  	schoolBeforeHTL,
	burgerPizzaAvocado,
	favouriteSubject,
	favouriteColor,
	phone,
	favouriteFood,
	favouriteMedia,
	specialClassFunction,
	socialmedia
) VALUES (
	"Michael",
	"Samarati",
	"2005-06-03",
	"190182@studierende.htl-donaustadt.at",
	"6",
	"michael_samarati.gif",
	"100%",
	"eine andere Farbe",
	"Nichts davon",
	"Aqua - Barbie Girl",
	"Chicken-Wings im Sale!!1 bei Lidl",
	"Netzwerktechnik-Maschine, der Router höchstpersönlich && Lieber im Stehen scheißen, als in der Scheiße stehen.",
	"Nachdenken",
	"Keine",
	"Keine",
	"NMS",
	"🥑",
	"ITP2",
	"#00fced",
	"Windows-Phone",
	"Pizza Hawaii",
	"Serien: Violet Evergarden; Alle hassen Chris; Filme: Die Eisprinzen; Der gezähmte Widerspenstige",
	"Klassenstreber",
	"https://github.com/MichaelSamarati"
);

INSERT INTO students (
	forename,
	lastname,
	birthday,
	email,
	siblings,
	imageName,
	visionScore,
	eyeColor,
	piercingTattoos,
	chickenCrossReason,
	quote,
	hobbies,
	pets,
	allergies,
  	schoolBeforeHTL,
	burgerPizzaAvocado,
	favouriteSubject,
	favouriteColor,
	phone,
	favouriteFood,
	favouriteMedia,
	specialClassFunction
) VALUES (
	"Taisir",
	"Khalifa",
	"2004-12-12",
	"190315@studierende.htl-donaustadt.at",
	"halt kein Einzelkind",
	"taisir_khalifa.jpg",
	"???",
	"braun",
	"Nichts davon",
	"To get to the other side",
	"3 kleine Mäus, schau wie sie rennen. Sie rannten zur Bäuerin unverwand..  die nahm ein Großes Messer in die Hand und hackte den Mäusen die Schwänze ab .. Hast du schon mal sowas gesehen gehabt wie drei blinde mäus.",
	"zu viele",
	"Keine",
	"Keine",
	"AHS",
	"🥑",
	"NW2",
	"#07f6e7",
	"Android",
	"...",
	"Detektiv Conan",
	"Klassenseele",
);

INSERT INTO students (
	forename,
	lastname,
	birthday,
	email,
	siblings,
	imageName,
	visionScore,
	eyeColor,
	piercingTattoos,
	favouriteSong,
	chickenCrossReason,
	quote,
	hobbies,
	pets,
	allergies,
  	schoolBeforeHTL,
	burgerPizzaAvocado,
	favouriteSubject,
	favouriteColor,
	phone,
	favouriteFood,
	favouriteMedia,
	specialClassFunction
) VALUES (
	"Philipp",
	"Vollmann",
	"2004-02-11",
	"180194@studierende.htl-donaustadt.at",
	"0",
	"philipp_vollmann.gif",
	"100%",
	"braun",
	"Nichts davon",
	"Aqua - Barbie Girl",
	"🖕",
	"Idk, I just got here",
	"Sportschutz-Training",
	"Ja",
	"Keine",
	"NMS",
	"🍕",
	"WIR3",
	"#096079",
	"iOS",
	"Spaghetti",
	"Tribute von Panem",
	"Repetent (der Klügere) & Gründervater der V-Mann-Gang"
);

INSERT INTO students (
	forename,
	lastname,
	birthday,
	email,
	siblings,
	imageName,
	visionScore,
	eyeColor,
	piercingTattoos,
	favouriteSong,
	chickenCrossReason,
	quote,
	hobbies,
	pets,
	allergies,
  	schoolBeforeHTL,
	burgerPizzaAvocado,
	favouriteSubject,
	favouriteColor,
	phone,
	favouriteFood,
	favouriteMedia,
	specialClassFunction,
	socialmedia
) VALUES (
	"Philipp",
	"Lueger",
	"2005-01-21",
	"190189@studierende.htl-donaustadt.at",
	"1",
	"philipp_lueger.gif",
	"100%",
	"eine andere Farbe",
	"Nichts davon",
	"lied",
	"To get to the other side",
	"Sein oder nicht sein, das ist hier die Frage",
	"TRINKEN GEHEN!",
	"Katze",
	"Keine",
	"AHS",
	"🍕",
	"SEW",
	"#c67979",
	"iOS",
	"Asiatisch",
	"Lucifer",
	"Abteilungssprecher; Klassensprecher",
	"https://www.linkedin.com/in/philipp-lueger/"
);



INSERT INTO students (
	forename,
	lastname,
	birthday,
	email,
	siblings,
	imageName,
	visionScore,
	eyeColor,
	piercingTattoos,
	chickenCrossReason,
	quote,
	hobbies,
	pets,
	allergies,
  	schoolBeforeHTL,
	burgerPizzaAvocado,
	favouriteSubject,
	favouriteColor,
	phone,
	favouriteFood,
	favouriteMedia,
	specialClassFunction
) VALUES (
	"Luka",
	"Ramljak",
	"2005-01-06",
	"190187@studierende.htl-donaustadt.at",
	"2",
	"luka_ramljak.gif",
	"100%",
	"braun",
	"Nichts davon",
	"Das Name des Pferdes war Freitag",
	"Wenn der Keks redet hat der Krümel zu schweigenö",
	"Mathe, Netzwerktechnik und Depressionen",
	"Keine",
	"Hausstaub und Katzen",
	"AHS",
	"🍕",
	"GGP",
	"#4169E1",
	"Android",
	"Hofer backbox kornspitz und argeta",
	"Malcom Mittendrin und die lore videos von fnaf by gametheory",
	"Immer Anwesend (ich bin ein sklave meiner disziplin)"
);



INSERT INTO comments (name,message,dat,studentid) 
VALUES ("Test User","Very good profile!😍💕😘", "2023-04-04", (select studentid from students where lastname="Samarati" LIMIT 1));

INSERT INTO comments (name,message,dat,studentid) 
VALUES ("Trashtalker","Huan 🤐🫠🫤😕😤", "2023-05-02", (select studentid from students where lastname="Samarati" LIMIT 1));


